version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped
    # Added for development
    environment:
      - DEV_MODE=true
      - DEV_TUNNEL_URL=https://w06z1rvh-80.inc1.devtunnels.ms

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    depends_on:
      - nginx
    networks:
      - app-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # Only run in production
    profiles: ["production"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://w06z1rvh-80.inc1.devtunnels.ms/api
      - NEXT_PUBLIC_HOSTNAME=w06z1rvh-80.inc1.devtunnels.ms
      - NEXTAUTH_URL=https://w06z1rvh-80.inc1.devtunnels.ms
      - NEXT_PUBLIC_BASE_URL=https://w06z1rvh-80.inc1.devtunnels.ms
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://w06z1rvh-80.inc1.devtunnels.ms
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
